circuit-example: circuit-example.cpp circuit.hpp
	g++ -std=c++14 -Wall -Wextra -Wconversion $< -o $@

context-example: context-example.cpp context-clear.hpp context.hpp circuit.hpp
	g++ -std=c++14 -Wall -Wextra -Wconversion $< -o $@
