find_path(PALISADE_INCLUDE_DIR NAMES palisade.h)
find_library(PALISADE_CORE_LIBRARY NAMES PALISADEcore)
find_library(PALISADE_PKE_LIBRARY NAMES PALISADEpke)
find_library(PALISADE_NTL_LIBRARY NAMES libntl.so.35)

#set(PALISADE_FOUND TRUE)
set(PALISADE_INCLUDE_DIRS ${PALISADE_INCLUDE_DIR})
set(PALISADE_LIBRARIES ${PALISADE_CORE_LIBRARY} ${PALISADE_PKE_LIBRARY} ${PALISADE_NTL_LIBRARY})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(PALISADE DEFAULT_MSG
                                  PALISADE_CORE_LIBRARY PALISADE_INCLUDE_DIR)

mark_as_advanced(PALISADE_CORE_LIBRARY PALISADE_PKE_LIBRARY PALISADE_NTL_LIBRARY PALISADE_INCLUDE_DIR)
